// Jasurbek 22, [4/2/2022 1:55 PM]
// GIN-debug] GET    /v1/admin-panel/users/    --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).GetUsers-fm (6 handlers)
// [GIN-debug] PUT    /v1/admin-panel/users/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).ConfigUser-fm (6 handlers)
// [GIN-debug] POST   /v1/admin-panel/super_categories/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PostSupCategory-fm (6 handlers)
// [GIN-debug] PUT    /v1/admin-panel/super_categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PutSupCategory-fm (6 handlers)
// [GIN-debug] DELETE /v1/admin-panel/super_categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.DeleteSupCategory-fm (6 handlers)
// [GIN-debug] POST   /v1/admin-panel/super_categories/categories/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PostCategory-fm (6 handlers)
// [GIN-debug] PUT    /v1/admin-panel/super_categories/categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PutCategory-fm (6 handlers)
// [GIN-debug] DELETE /v1/admin-panel/super_categories/categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.DeleteCategory-fm (6 handlers)
// [GIN-debug] POST   /v1/admin-panel/super_categories/categories/sub_categories/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PostSubCategory-fm (6 handlers)
// [GIN-debug] PUT    /v1/admin-panel/super_categories/categories/sub_categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PutSubCategory-fm (6 handlers)
// [GIN-debug] DELETE /v1/admin-panel/super_categories/categories/sub_categories/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.DeleteSubCategory-fm (6 handlers)
// [GIN-debug] POST   /v1/auth/sign-up          --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.SignUP-fm (4 handlers)
// [GIN-debug] POST   /v1/auth/authorization    --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.Auth-fm (4 handlers)
// [GIN-debug] POST   /v1/auth/log-in           --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.Login-fm (4 handlers)
// [GIN-debug] GET    /v1/profile/              --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).GetProfile-fm (5 handlers)
// [GIN-debug] PUT    /v1/profile/edit          --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).PutProfile-fm (5 handlers)
// [GIN-debug] PUT    /v1/profile/change_number --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).ChangePhoneNumber-fm (5 handlers)
// [GIN-debug] PUT    /v1/profile/change_password --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).ChangePassowrd-fm (5 handlers)
// [GIN-debug] POST   /v1/profile/add-new-plant/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PostPlant-fm (5 handlers)
// [GIN-debug] PUT    /v1/profile/add-new-plant/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.PutPlant-fm (5 handlers)
// [GIN-debug] DELETE /v1/profile/add-new-plant/:id --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.DeletePlant-fm (5 handlers)
// [GIN-debug] POST   /v1/profile/add-new-plant/:id/add-image/ --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).PostImages-fm (5 handlers)
// [GIN-debug] DELETE /v1/profile/add-new-plant/:id/add-image/:iid --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).DelImage-fm (5 handlers)
// [GIN-debug] GET    /v1/places/regioins/      --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).GetRegions-fm (4 handlers)
// [GIN-debug] GET    /v1/places/regioins/:id/districts --> github.com/JasurbekUz/ficus/api/handlers/v1.(*handler).GetDistricts-fm (4 handlers)
// [GIN-debug] GET    /v1/places/regioins/:id/districts/:did/plants --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetPlants-fm (4 handlers)
// [GIN-debug] GET    /v1/places/regioins/:id/districts/:did/plants/:pid --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetPlant-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/     --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetSupCategories-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id  --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetSupCategory-fm (4 handlers)

// Jasurbek 22, [4/2/2022 1:55 PM]
// [GIN-debug] GET    /v1/super_categories/:id/categories/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetCategories-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id/categories/:cid --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetCategory-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id/categories/:cid/sub_categories/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetSubCategories-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id/categories/:cid/sub_categories/:sid --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetSubCategory-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id/categories/:cid/sub_categories/:sid/plants/ --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetPlants-fm (4 handlers)
// [GIN-debug] GET    /v1/super_categories/:id/categories/:cid/sub_categories/:sid/plants/:pid --> github.com/JasurbekUz/ficus/api/handlers/v1.handler.GetPlant-fm (4 handlers)
